// Connpass Event Info Extractor Bookmarklet
// Extracts event information from a Connpass event page and copies it to the clipboard in Markdown format.

// This code was generated by GitHub Copilot Agent Mode using Claude Sonnet 4.

javascript:(function(){
    const ogTitle = document.querySelector('meta[property="og:title"]');
    const eventTitle = ogTitle.getAttribute('content').replace(/\s*\([^)]*\)\s*$/, '');

    let groupName = "";
    const eventOwner = document.querySelector('.event_owner');
    if (eventOwner) {
        groupName = eventOwner.textContent.trim().replace(/^主催\s*[:：]\s*/, '');
    } else {
        const groupElement = document.querySelector('.group_title');
        groupName = groupElement.textContent.trim();
    }
    
    const ymdElement = document.querySelector('.ymd');
    const eventDate = ymdElement.textContent.trim().replace(/\([^)]*\)/, '');
    
    const ogUrl = document.querySelector('meta[property="og:url"]');
    const connpassUrl = ogUrl.getAttribute('content');
    
    const markdownText = `- （${eventDate}）${groupName}主催、${eventTitle} [＜connpass＞](${connpassUrl}) [＜イベントページ＞]() [＜YouTube＞]() ＜YouTubeアーカイブ動画あり＞`;
    
    navigator.clipboard.writeText(markdownText);
})();
