
// Extracts event date, organizer, and event name from a Connpass event page.
// Outputs in a filename-safe format: YYYYMMDD_Organizer_EventName.
// The output can be copied to the clipboard.

// This code was generated by GitHub Copilot Agent Mode using Claude Sonnet 4 and GPT-4.1.

javascript:(function(){
    const ogTitle = document.querySelector('meta[property="og:title"]');
    const eventTitle = ogTitle.getAttribute('content').replace(/\s*\([^)]*\)\s*$/, '');
    
    let groupName = "";
    const eventOwner = document.querySelector('.event_owner');
    if (eventOwner) {
        groupName = eventOwner.textContent.trim().replace(/^主催\s*[:：]\s*/, '');
    } else {
        const groupElement = document.querySelector('.group_title');
        groupName = groupElement.textContent.trim();
    }
    
    const ymdElement = document.querySelector('.ymd');
    const eventDate = ymdElement.textContent.trim().replace(/\([^)]*\)/, '').replace(/\//g, '');
    
    const output = `${eventDate}_${groupName}_${eventTitle}_YouTube`.replace(/[\\/:*?"<>| ]/g, '');
    
    navigator.clipboard.writeText(output);
})();
